# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f30a2af4d37f127568f0bbadee08e15a97298ae65c178222a39e0ee2df118d4e0ae3f8c1883497ed78f9f557b88f77c306e14c7d1473d6fd893ffc3b242f2459

test:
  secret_key_base: da09b7152919ad68bd3ed4e3f9c9b1da6c0f2f80890ff72cf36c491c9ab987a79bfd88f9f9b7381b234876e4308e7782f103807e5d192553e60b7d14a7734a26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
